---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=fis-spring-boot-camel-amq&var-version=1.0-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "fis-spring-boot-camel-amq"
    version: "1.0-SNAPSHOT"
    group: "org.example.fis"
  name: "fis-spring-boot-camel-am"
spec:
  replicas: 1
  selector:
    project: "fis-spring-boot-camel-amq"
    provider: "fabric8"
    group: "org.example.fis"
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: "Rolling"
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: "img/icons/camel.svg"
        fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=fis-spring-boot-camel-amq&var-version=1.0-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "fis-spring-boot-camel-amq"
        version: "1.0-SNAPSHOT"
        group: "org.example.fis"
    spec:
      containers:
      - env:
        - name: "ACTIVEMQ_SERVICE_NAME"
          value: "broker-amq-tcp"
        - name: "ACTIVEMQ_BROKER_USERNAME"
          value: "admin"
        - name: "ACTIVEMQ_BROKER_PASSWORD"
          value: "admin"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fis/fis-spring-boot-camel-amq:snapshot-180703-200105-0820"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 180
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
  triggers:
  - type: "ConfigChange"
